AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: provided.al2
    Architectures:
    - arm64
    Handler: bootstrap
    MemorySize: 512
    Timeout: 90
    AutoPublishAlias: live
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: go-aws-lambda-sample
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
    Metadata:
      SamResourceId: LambdaRole
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: go-aws-lambda-sample
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      CodeUri: s3://test-n-yuta/b37c71e49c5ba06fe18e620230decac0
    Metadata:
      BuildMethod: makefile
      SamResourceId: Function
